source:
  copy_from:
    - "README.md"
    - ".gitignore"
    - "build-book.yml"
    - "requirements.txt"
    - "LICENSE"
    - "LICENSE-CC-BY-SA"
    - "CITATION.cff"
    - "mdmc"
    - ".publish"
target:
  repo: "lcbc-epfl/mdmc-public"
  maxsize_commit_MB: 1000
  commit_message: "publish student version"
  copy_to:
    - "README.md"
    - ".gitignore"
    - ".github/workflows/build-book.yml"
    - "requirements.txt"
    - "LICENSE"
    - "LICENSE-CC-BY-SA"
    - "CITATION.cff"
    - "mdmc"
    - ".publish"
  remove_after_copy:
    - "mdmc/Ex5/ToyMD/*"
    - "mdmc/Ex5/ToyMD.zip"
