#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Molecular Dynamics and Monte Carlo  
author                      : Simon Duerr, Sophie Johnson, Irea Mosquera, Andrea Levy,  Ursula Roethlisberger  # The author of the book
only_build_toc_files        : true
execute:
  execute_notebooks: 'off'
  #exclude_patterns:
  #  - 'Ex*/*_Solution*'
  #  - 'Ex*/*_solution*'
bibtex_bibfiles:
   - references.bib
parse:
  #myst_extended_syntax: true
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
repository:
  url                       : https://github.com/lcbc-epfl/mdmc-public  # Online location of your book
  branch                    : main
  path_to_book:               mdmc 
launch_buttons:
  notebook_interface        : jupyterlab
  jupyterhub_url: "https://noto.epfl.ch"
  colab_url: "https://colab.research.google.com"
  binderhub_url:  ""
html:
  use_issues_button: true
  use_multitoc_numbering: false
  use_repository_button: true
  extra_footer              :   # Will be displayed underneath the footer.
    <div class="container-lg mt-3 footer">
      <div class="row">
        <div class="col-xl-9 d-flex">
          <div class="container">
            <div class="row">
              <div class="col-6 d-flex" style="justify-content:center">
            <a href="https://lcbc.epfl.ch"> Laboratory of Computational Biochemistry and Chemistry</a></li>

              </div>
              <div class="col-6 d-flex" style="justify-content:center">
                <ul style="list-style:none">
                  <li> <a href="https://github.com/lcbc-epfl/mdmc-public">GitHub </a> </li> </li>
                  <!--<li> <a href="https://doi.org/10.5281/zenodo.0000000"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.00000000.svg" alt="DOI"></a> </li>-->
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-3">
          <a href="https://epfl.ch"><img src="https://www.epfl.ch/wp/5.5/wp-content/themes/wp-theme-2018/assets/svg/epfl-logo.svg?refresh=now" alt="EPFL Logo" style="padding:5px;height:33px;"></a>
        </div>
      </div>
    </div>
    <div class="row_footer my-3">
      Dual licensed under the <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank">Creative Commons Attribution Share Alike 4.0 International</a> (CC BY SA 4.0) and MIT license. (Except where indicated otherwise)
    </div>
sphinx: 
    config:
        language: en
        html_show_copyright: false
        mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
        mathjax_config:
            TeX:
              Macros:
                "ket": ["\\lvert #1 \\rangle",1]
                "bra": ["\\langle #1 \\lvert",1]
                "Ket": ["\\lvert #1 \\rangle",1]
                "Bra": ["\\langle #1 \\lvert",1]
                "braket": ["\\langle #1 \\lvert #2 \\rangle",2]
                "hop": "\\hat{\\mathcal{H}}"
                "unit": "\\mathbbm{1}"

