name: build-book

# Only run this when the master branch changes
on:
  push:
    branches:
    - deploy
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: convert md to slides
      run: |
        docker run -v $(pwd):/data --user $(id -u):$(id -g) pandoc/latex:2.9 sh -c 'while read f; do pandoc -t beamer /data/mdmc/"$f" -H /data/.publish/template.tex -o "/data/mdmc/${f%}.pdf"; done< mdmc/slides.txt'

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build mdmc
    - name: Move slides to publish dir
      run: | 
        while read f; do mv "./mdmc/${f%}.pdf" "./mdmc/_build/html/${f%}.pdf"; done< ./mdmc/slides.txt
    - name: Copy pdb files
      run: |
          cp mdmc/Ex6/*.pdb mdmc/_build/html/Ex6/
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mdmc/_build/html
